### ISSUE TITLE
chore(deps): update kinsondigital/infrastructure action to v14

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Plazma#14]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Set up any workflows to run status checks, the syncing system, and preview and production releases.

### Acceptance Criteria

- [x] Workflows created for status checks
- [x] Workflows created for syncing system
- [x] Workflow created for performing prev and prod releases
- [x] Set up vscode settings
- [x] Add any dictionary words for rider
- [x] Add all solution items for rider
- [x] Update editor configs

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
