### ISSUE TITLE
🚧Create Social Preview

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Plazma#15]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a Social Preview that includes the new logo.

### Acceptance Criteria

- [ ] Social Preview set up

One idea is to have a black or almost full black background with white dots with a radial gradient scattered in a random pattern.  On top of this would be the main plazma logo.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Issue Dependencies

- #2 

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
