### ISSUE TITLE
🚧Process all warnings

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Plazma#17]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Process all warnings in the project to improve and update the code to follow the current coding standards and recommendations.

### Acceptance Criteria

- [x] All warnings processed 
- [x] Refactor the `ParticleEffect.BurstOnTime` prop to `ParticleEffect.BurstOnMilliseconds`
- [x] Refactor the `ParticleEffect.BurstOffMilliseconds` prop to `ParticleEffect.BurstOffMilliseconds`
- [x] Convert all unit tests to use FluentAssertions

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [X] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
