### ISSUE TITLE
🚧Replace moq code with nsubstitute

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Plazma#21]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace mock with NSubstitute.  This will prevent any incoming update prs from renovate until we can find the time to possibly move away from MOQ

This is due to the reason for preventing the practice of harvesting PII.  This is a recent change that the MOQ project has added to _**v4.20.+**_.

For more information go to:
- moq/moq#1372

### Acceptance Criteria

- [x] Moq nuget package removed from project
- [x] All moq code replaced with NSubstitute code
- [x] After pr is merged, update **_CICD_SCRIPTS_VERSION_** repo var

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
