### ISSUE TITLE
🚧Add manual test project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Plazma#23]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a test project to facilitate manual testing by using Velaptor.

This used to exist before by using a MonoGame project but has recently been removed for the eventual replacement of Velaptor.

### Acceptance Criteria

- [x] Velaptor project created for manual testing
- [x] Add build job to the build status check workflow for the new project

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
