### ISSUE TITLE
🚧Add new features and improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Plazma#25]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the following features and improvements:

1. Convert the behavior system to use a composable model instead of an inheritance model.
    The behavior settings all need to be converted to read-only record structs with the combined use of an `IBehaviorSettings` interface.
    - This will give a performance benefit as well as create something composable due to the interface.  This will also give people the ability to create custom behaviors.
1. Setup the behaviors to easily be swapped out with another behavior

### Acceptance Criteria

- [x] Behavior system converted
- [x] Behavior swapping added

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
